sonar.projectKey=your-github-username_customer-registration-agents-api
sonar.organization=kingposhwolf

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.java.libraries=build/libs
sonar.sourceEncoding=UTF-8
sonar.java.source=21