sonar.projectKey=kingposhwolf_customer-registration-agents-api
sonar.organization=kingposhwolf

sonar.projectName=Customer Registration Agents API
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8
sonar.java.source=21

# Exclude files
sonar.exclusions=**/build/**,**/*.gradle