spring.application.name=customer-registration-agents-api

#Datasource (DB Connection)
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/customer_registration_agent
spring.datasource.username=postgres
spring.datasource.password=Manka2002@
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true